# Generated by Django 6.0.5 on 2026-06-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=250)),
                ('t_desc', models.TextField(default='')),
                ('priority', models.CharField(choices=[('HIGH', 'high'), ('LOW', 'low'), ('AVERAGE', 'average')], max_length=250)),
            ],
        ),
    ]
