# Generated by Django 6.0.5 on 2026-06-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profilephoto',
            field=models.ImageField(upload_to='media/userphoto/'),
        ),
    ]
