# Generated by Django 6.0.5 on 2026-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_id_myuser_id_alter_myuser_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
